Team service and facade
fprochazka/fi-muni-PA165-project pull request #42
Opened 2016-11-17 20:39 UTC by ATP93

2016-11-22 18:24 UTC, fprochazka requested changes

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/Team.java
>          this.name = name;
assert not null

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/TeamFacade.java
> +        query = entityManager.createQuery("DELETE FROM TeamMatch tm WHERE tm.awayTeam = :tid OR " +
Tady to reusovani lokální proměnné by tady ideálně být nemělo, protože to jsou různé query. 

Ostatně, dá se to napsat i jako jeden fluent a pak lokální proměnná není potřeba vubec

```java
entityManager
    .createQuery("DELETE FROM TeamMatch tm WHERE tm.awayTeam = :tid OR tm.homeTeam = :tid")
    .setParameter("tid", team)
    .executeUpdate();
```

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/TeamRepository.java
> +    Team getTeamById(UUID id);
prosil bych všechny parametry v repository jako final (i v implementaci)

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/TeamService.java
> +    public TeamService()
prazdnej konstruktor neni potřeba ne?

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/main/resources/application-context.xml
> +<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
proč jsi tohle měnil?

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/test/java/cz/muni/fi/pa165/team/TeamFacadeTest.java
> +        assertNotNull(foundTeam);
kdyz napíšeš test na to, že ta `getTeamById` háže výjimku, pokud nenajde team, tak tady tenhle assert na null nebude potřeba

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/test/java/cz/muni/fi/pa165/team/TeamFacadeTest.java
> +            Team foundTeam = teamRepository.getTeamById(tmpId);
použil bych `entityManager.find(Team.cass, tmpId)`, protože tady chceš testovat, že to fasáda smazala, ne že se vyhodí správná výjimka

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/test/java/cz/muni/fi/pa165/team/TeamFacadeTest.java
> +        em.clear();
tady neni potřeba ten clear, protože hledáš podle ruzneho jmena a nic nemodifikuješ... nevadí ničemu, ale ani neni potřeba :)

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/test/java/cz/muni/fi/pa165/team/TeamRepositoryImplTest.java
>      public void findById()
špatný název

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/test/java/cz/muni/fi/pa165/team/TeamRepositoryImplTest.java
> +        Assert.assertNotNull(teamDao.getTeamById(t2.getId()));
chtělo by to ještě jeden test na to, že to vyhodi vyjimku, viz předchozí komentáře

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/test/java/cz/muni/fi/pa165/team/TeamFacadeTest.java
> +    public TeamService teamService;
nevidím, že bys to někde v té třídě používal

2016-11-22 18:24 UTC, fprochazka commented on soccer-records-model/src/test/java/cz/muni/fi/pa165/team/TeamFacadeTest.java
> +        Team foundTeam2 = teamRepository.findTeamByName("ManUtd");
říkám si, že ty find věci v testech by bylo lepší dělat rovnou přes entityManager... vím že to tam taky mám, ale uvědomil jsem si to až teď... jdu to předělat :)

2016-11-22 18:24 UTC, fprochazka commented
A ještě to pak rebasni na master jednou, až to budeš mít hotové :)

2016-11-22 18:26 UTC, fprochazka commented
A ještě koukám, že jak jsi se snažil začlenit master (rebasnut na něj), tak se ti to moc nepovedlo

![image](https://cloud.githubusercontent.com/assets/158625/20536455/6fdac2e8-b0e9-11e6-9c5b-c887a70e4387.png)

ale když to rebasneš správně, tak by to mělo zmizet

* commitnout práci
* checkout master
* pull origin master
* checkout moje větev
* rebase master
* vyřešit konflikty
* forcepush

2016-11-22 18:54 UTC, ATP93 commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/TeamFacade.java
> +        query = entityManager.createQuery("DELETE FROM TeamMatch tm WHERE tm.awayTeam = :tid OR " +
niesom si celkom isty co tym presne myslis. tie 3 delety prepisat do jedneho?

2016-11-22 19:05 UTC, ATP93 commented on soccer-records-model/src/main/resources/application-context.xml
> +<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
IDEA mi zmenila sama

2016-11-22 19:31 UTC, ATP93 commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/TeamService.java
> +    public TeamService()
pravda, pravda - prehliadol som ho, vdaka

2016-11-22 20:25 UTC, fprochazka commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/TeamFacade.java
> +        query = entityManager.createQuery("DELETE FROM TeamMatch tm WHERE tm.awayTeam = :tid OR " +
Ne psat do jednoho, ale aby se 

1. neznovupoužívala stejná proměnná na různé query, ale aby kazda query měla jinou proměnou definovanou
2. za bonus je když lokalni proměnnou na `query` vubec nepoužiješ a napíšeš to stylem jako jsem posílal výše

2016-11-22 20:51 UTC, ATP93 commented on soccer-records-model/src/main/java/cz/muni/fi/pa165/team/TeamFacade.java
> +        query = entityManager.createQuery("DELETE FROM TeamMatch tm WHERE tm.awayTeam = :tid OR " +
jasne, vdaka, uz rozumiem, zle som ta pochopil - myslel som, ze poukazujes na pouzitie lokalnej premennej team.

2016-11-24 21:56 UTC, fprochazka approved these changes

2016-11-24 22:00 UTC, merged