Ts match web
fprochazka/fi-muni-PA165-project pull request #69
Opened 2017-01-08 19:03 UTC by TomasSmid

2017-01-08 22:08 UTC, fprochazka requested changes

2017-01-08 22:08 UTC, fprochazka commented on model/src/main/java/cz/muni/fi/pa165/team/match/TeamMatchFacade.java
> +            mr.setMatch(pm);
nebylo by lepší mít jen konstruktor a vubec zadne settery?

2017-01-08 22:08 UTC, fprochazka commented on model/src/main/java/cz/muni/fi/pa165/team/match/result/MatchResult.java
> +    public void setMatch(TeamMatch match)
myslim že neni zadny duvod aby tenhle objekt byl mutable

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchRequest.java
> +    public String homeTeamId;
pokud se nepletu, tak by spring měl umět mapovat request objekty na libovolné typy, nejenom stringy, takže bych zkusil, jestli tady nejde dat UUID plus nejaky validace že je to valid

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +            if (request.getAwayTeamId() == null) {
tohle jde udělat pomoci `@NotNull` annotace nad request objektem

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +            if (request.getHomeTeamId() == null) {
tohle jde udělat pomoci `@NotNull` annotace nad request objektem

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchRequest.java
> +    public String startTime;
tohle nejde konvertovat rovnou na `LocalDateTime`?

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +    private LocalDateTime getMVCLocalDateTime(String formInputDate)
moc se mi nelibi, že by tohle bylo v každém controlleru, zkus pls vyzkoumat, jestli to fakt nejde automatizovaně mapovat na tom request objektu

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +    private LocalDateTime getMVCLocalDateTime(String formInputDate)
pokud to nepůjde, udělal bych statický helper, ktery bych volal v getterech request objektu, aby rovnou vracely správný typ a nemuselo se to převádět v controllerech

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/upcomming.jsp
> +                                             <td><c:out value=" - "/></td>
tady asi chybí ještě ty počty golu, ne?

2017-01-08 22:08 UTC, fprochazka commented on web/src/main/webapp/resources/css/main.css
> +#form-buttons {
Pokus se pls nepoužívat css idčka, raději classy. Navíc zrovna na tohle je v bootstrapu class [`text-right`](https://v4-alpha.getbootstrap.com/utilities/typography/#text-alignment) kterou stačí dát tomu elementu a tedy neni potřeba vubec definovat nove ID ani CLASS

2017-01-08 23:28 UTC, TomasSmid commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchRequest.java
> +    public String startTime;
zkusim to rano zjistit, ale osobne myslim, ze ne...

2017-01-08 23:29 UTC, TomasSmid commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +    private LocalDateTime getMVCLocalDateTime(String formInputDate)
dival jsem se na to, zatim jsem na nic extra kloudneho neprisel, zkusim to jeste vyresit, kdyz nic nevymyslim, udelam to pak treba do tech getteru...

2017-01-08 23:32 UTC, TomasSmid commented on web/src/main/webapp/WEB-INF/jsp/team/match/upcomming.jsp
> +                                             <td><c:out value=" - "/></td>
no, puvodne to tam bylo, ted jsem to ale dal pryc a to proto, ze jsem si rikal, ze v nadchazejicich zapasech jeste prece zadny gol padnout nemohl, ALE ted me napada, ze jako nadchazejici zapas muze byt oznaceny i nejaky prave probihajici zapas, ke kteremu se postupne pridavaji goly, tedy pokud by to takto melo smysl, potom to tam dodelam, pokud ne, pak je to spravne...

2017-01-08 23:33 UTC, TomasSmid commented on web/src/main/webapp/resources/css/main.css
> +#form-buttons {
ok, no popravde se se styly nechci nejak zatezovat, jen prebiram to, co bylo k navrhu sablony dodano a melo to svym zpusobem plnit svuj ucel...

2017-01-09 11:39 UTC, TomasSmid commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +            if (request.getHomeTeamId() == null) {
Kde presne by se ta anotace @NotNull mela pouzit? zkousel jsem to pouzit nad atributy request objektu (protoze ne vsechny atributy nemuzou byt null), ale to rozhodne nefunguje...

2017-01-09 17:24 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +            if (request.getHomeTeamId() == null) {
u te property na tom request objektu

2017-01-09 17:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/upcomming.jsp
> +                                             <td><c:out value=" - "/></td>
domluveno na messengeru, že to byla blbost :) nechal bych jen `<td> - </td>`

2017-01-10 17:59 UTC, TomasSmid commented on web/src/main/webapp/WEB-INF/jsp/team/match/upcomming.jsp
> +                                             <td><c:out value=" - "/></td>
jo to je spraveno...

2017-01-10 20:35 UTC, fprochazka requested changes

2017-01-10 20:35 UTC, fprochazka commented on model/src/main/java/cz/muni/fi/pa165/team/match/auxobjects/MatchDetailView.java
> +package cz.muni.fi.pa165.team.match.auxobjects;
jak jsi přišel na tenhle namespace?

2017-01-10 20:35 UTC, fprochazka commented on model/src/main/java/cz/muni/fi/pa165/team/match/TeamMatchFacade.java
> +        return new MatchDetailView(
`*Result`?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/create.jsp
> +                                 <sec:authorize access="hasAnyRole('ROLE_ADMIN', 'ROLE_MODERATOR')">
tohle sem nepatří.. tím že schováš button nezakážeš odeslání formuláře.. to se musí udělat annotací v controlleru, aby ses vubec na takovy view nedostal

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +    public ModelAndView deleteMatch(@PathVariable("id") UUID id) throws Exception
tady je potřeba dořešit oprávnění už na urovni controlleru

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +    public ModelAndView deleteGoal(@PathVariable("mid") UUID mid, @PathVariable("gid") UUID gid)
tady je potřeba dořešit oprávnění už na urovni controlleru

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                                        <div class="modal fade" id="deleteAwayGoalModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:
buďto to `aria-` vyplň něčím rozumným, nebo ten attribut smaž.. slouží to jako pomoc pro čtečky pro nevidomé

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                                        <div class="modal fade" id="deleteHomeGoalModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:
buďto to `aria-` vyplň něčím rozumným, nebo ten attribut smaž.. slouží to jako pomoc pro čtečky pro nevidomé

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                        <a href="<c:url value="/match/${matchResult.match.id}/goal/create"/>" class="btn btn-outline-primary pull-right" data-dismiss="modal">Add Goal</a>
proč máš tady ten dismiss modal?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                    <div class="container">
tohle už by neměl být container, ne? imho je to zbytecne a stači ten vnitřní `row`

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                        <a href="<c:url value="/match/${matchResult.match.id}/goal/create"/>" class="btn btn-outline-primary pull-right" data-dismiss="modal">Add Goal</a>
tady taky, ten dismiss je zbytečný, ne?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                    <div class="modal fade" id="deleteMatchModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
`aria-`

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                                <input id="psubmit" name="submit" type="submit" class="btn btn-success" value="Delete">
proč těm `input` a `a` elementům dáváš `id`? na nic to nepoužíváš, ne?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                            <a href="match_form.html" class="btn btn-success">Edit</a>
`.html` ?  co to je za divny odkaz?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +    public ModelAndView viewEditMatch(@PathVariable("id") UUID id)
oprávnění

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +    public ModelAndView submitEditMatch(
oprávnění

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +            System.out.println("RESULT HAS ERROR, CYCLE INFINITE");
jaky cyklus? :D

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/MatchController.java
> +        System.out.println("CHANGE MATCH TIME");
?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/edit.jsp
> +                                                 <form:option value="${team.id}" label="${team.name}" selected="${team.id.equals(matchRequest.homeTeamId) ? 'selected' : ''}" disabled="${!team.id.equa
tohle neni jedina kontrola, že ty data jsou správně, že? ještě se to kontroluje i v modelu?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/edit.jsp
> +                                                 <form:option value="${team.id}" label="${team.name}" selected="${team.id.equals(matchRequest.awayTeamId) ? 'selected' : ''}" disabled="${!team.id.equa
tohle neni jedina kontrola, že ty data jsou správně, že? ještě se to kontroluje i v modelu?

2017-01-10 20:35 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/edit.jsp
> +                                    <input id="emsubmit" name="submit" type="submit" class="btn btn-success mbuttons" value="Save">
tady to id je zase zbytečné, ne?

2017-01-10 21:24 UTC, TomasSmid commented on model/src/main/java/cz/muni/fi/pa165/team/match/auxobjects/MatchDetailView.java
> +package cz.muni.fi.pa165.team.match.auxobjects;
spechal jsem a lepsi me v tu chvili nic nenapadlo...

2017-01-10 21:24 UTC, fprochazka requested changes

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/goal/GoalController.java
> +    public ModelAndView submitNewGoal(
security?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/java/cz/muni/fi/pa165/team/match/goal/GoalController.java
> +    public ModelAndView deleteGoal(@PathVariable("mid") UUID matchId, @PathVariable("gid") UUID goalId)
security?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                        <a href="<c:url value="/match/${matchResult.match.id}/team/${matchResult.match.homeTeam.id}/goal/create"/>" class="btn btn-outline-primary pull-right" data-dis
ten dismiss je potřeba?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                        <a href="<c:url value="/match/${matchResult.match.id}/team/${matchResult.match.awayTeam.id}/goal/create"/>" class="btn btn-outline-primary pull-right" data-dis
ten dismiss je potřeba?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/goal/create.jsp
> +                    <form:form class="form-horizontal match-form" id="goal-form" method="post" modelAttribute="goalRequest" action="${requestScope['javax.servlet.forward.request_uri']}" autocomplete=
to idčko je na něco dobré?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/goal/create.jsp
> +                            <legend id="match-form-legend">New goal creation form</legend>
taky, to id je na něco potřeba?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/goal/create.jsp
> +                                                         <form:option value="${scorer.id}" label="${scorer.firstname} ${scorer.surname}" selected="${scorer.id.equals(goalRequest.scorerId) ? 'selected
máme v modelu validaci, že scorer je ze spravneho tymu?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/goal/create.jsp
> +                                <sec:authorize access="hasAnyRole('ROLE_ADMIN', 'ROLE_MODERATOR')">
tohle tady být vubec nemusi, protože jakmile zabezpečíš tu akci, vubec se na tu stranku nedostane

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/goal/create.jsp
> +                                <a href="<c:url value="/match/${match.id}"/>" class="btn btn-secondary mbuttons" role="button" id="gcancel">Cancel</a>
to idčko je potřeba?

2017-01-10 21:24 UTC, fprochazka commented on web/src/main/webapp/WEB-INF/jsp/team/match/goal/create.jsp
> +                                    <input id="gsubmit" name="submit" type="submit" class="btn btn-success mbuttons" value="Save">
to idčko je potřeba?

2017-01-10 21:25 UTC, TomasSmid commented on web/src/main/webapp/WEB-INF/jsp/team/match/detail.jsp
> +                                                <input id="psubmit" name="submit" type="submit" class="btn btn-success" value="Delete">
jo dam pryc, to bude pozustatek jeste z navrhu..

2017-01-10 21:28 UTC, TomasSmid commented on web/src/main/webapp/WEB-INF/jsp/team/match/edit.jsp
> +                                                 <form:option value="${team.id}" label="${team.name}" selected="${team.id.equals(matchRequest.homeTeamId) ? 'selected' : ''}" disabled="${!team.id.equa
ale toto je kontrola jen pro vizualni dilo, ze se ti vybere v seznamu ten spravny zapas a ne vzdy select moznost ;) v modelu jsou pokud vim vsechny dulezite kontroly implementovany...

2017-01-10 21:28 UTC, TomasSmid commented on web/src/main/webapp/WEB-INF/jsp/team/match/edit.jsp
> +                                                 <form:option value="${team.id}" label="${team.name}" selected="${team.id.equals(matchRequest.awayTeamId) ? 'selected' : ''}" disabled="${!team.id.equa
jojo

2017-01-10 21:42 UTC, TomasSmid commented on web/src/main/webapp/WEB-INF/jsp/team/match/goal/create.jsp
> +                                                         <form:option value="${scorer.id}" label="${scorer.firstname} ${scorer.surname}" selected="${scorer.id.equals(goalRequest.scorerId) ? 'selected
na zaklade vstupnich parametru neni jak otestovat, zda je dany strelec ci asistent golu ze spravneho tymu, musel by se pridat atribut "skorujici tym", pak by to bylo proveditelne, tedy to udelam...

2017-01-12 15:43 UTC, fprochazka approved these changes

2017-01-12 15:43 UTC, merged

2017-01-12 15:43 UTC, fprochazka commented
:+1: